// hooks/useRecurring.jsx
import { useEffect } from "react";

export function useRecurring(expenses, setExpenses, incomes, setIncomes) {

  useEffect(() => {
    const now = new Date();

    // ── EXPENSES ──
    const newExpenses = [];

    expenses.forEach((item) => {
      if (!item.recurring || item.recurring === "none") return;

      const last      = new Date(item.date);
      const diffDays  = (now - last) / (1000 * 60 * 60 * 24);
      const threshold = item.recurring === "weekly" ? 7 : 30;

      if (diffDays >= threshold) {
        newExpenses.push({
          ...item,
          id:            Date.now() + Math.random(),
          date:          now.toISOString(),
          autoGenerated: true,
        });
      }
    });

    if (newExpenses.length > 0)
      setExpenses((prev) => [...newExpenses, ...prev]);

    // ── INCOMES ──
    const newIncomes = [];

    incomes.forEach((item) => {
      if (!item.recurring || item.recurring === "none") return;

      const last      = new Date(item.date);
      const diffDays  = (now - last) / (1000 * 60 * 60 * 24);
      const threshold = item.recurring === "weekly" ? 7 : 30;

      if (diffDays >= threshold) {
        newIncomes.push({
          ...item,
          id:            Date.now() + Math.random(),
          date:          now.toISOString(),
          autoGenerated: true,
        });
      }
    });

    if (newIncomes.length > 0)
      setIncomes((prev) => [...newIncomes, ...prev]);

  }, []); // runs once on mount — checks on every app load
}