import { useState } from "react";
import { RefreshCw, Download, FileText, Pencil, Trash2, Tag, Clock } from "lucide-react";
import { useApp }        from "../context/AppContext";
import ExpenseForm       from "../components/ExpenseForm";
import EmptyState        from "../components/EmptyState";
import ConfirmModal      from "../components/ConfirmModal";
import DateRangeFilter   from "../components/DateRangeFilter";
import { useExport }     from "../hooks/useExport";

const FILTER_OPTIONS = [
  { key: "all",   label: "All Time", icon: "∞" },
  { key: "today", label: "Today"               },
  { key: "week",  label: "This Week"           },
  { key: "month", label: "This Month"          },
];

function Expenses({ toast }) {

  const { expenses, setExpenses, search, fmt } = useApp();

  const [editId,   setEditId]   = useState(null);
  const [editData, setEditData] = useState({
    title: "", category: "", amount: "", date: "", recurring: "none"
  });
  const [filter,    setFilter]    = useState("all");
  const [dateRange, setDateRange] = useState(null); // { from, to }

  const [confirmOpen,       setConfirmOpen]       = useState(false);
  const [pendingDeleteId,   setPendingDeleteId]   = useState(null);
  const [pendingDeleteName, setPendingDeleteName] = useState("");

  const { exportCSV, exportPDF } = useExport();

  // ================= ADD =================
  const addExpense = (exp) => {
    const formatted = {
      ...exp,
      title: exp.title
        ? exp.title.charAt(0).toUpperCase() + exp.title.slice(1)
        : exp.title,
    };
    setExpenses([{ id: Date.now(), recurring: "none", ...formatted }, ...expenses]);
    toast?.({ message: `✅ "${formatted.title}" added`, type: "success" });
  };

  // ================= DELETE =================
  const askDelete = (item) => {
    setPendingDeleteId(item.id);
    setPendingDeleteName(item.title);
    setConfirmOpen(true);
  };

  const confirmDelete = () => {
    setExpenses(expenses.filter((e) => e.id !== pendingDeleteId));
    toast?.({ message: `🗑 "${pendingDeleteName}" deleted`, type: "error" });
    setConfirmOpen(false);
    setPendingDeleteId(null);
    setPendingDeleteName("");
  };

  const cancelDelete = () => {
    setConfirmOpen(false);
    setPendingDeleteId(null);
    setPendingDeleteName("");
  };

  // ================= EDIT =================
  const startEdit = (item) => {
    setEditId(item.id);
    setEditData({
      title:     item.title     || "",
      category:  item.category  || "",
      amount:    item.amount    || "",
      date:      item.date ? new Date(item.date).toISOString().slice(0, 16) : "",
      recurring: item.recurring || "none",
    });
  };

  const saveEdit = () => {
    const updated = {
      ...editData,
      title: editData.title
        ? editData.title.charAt(0).toUpperCase() + editData.title.slice(1)
        : editData.title,
    };
    setExpenses(expenses.map((e) => e.id === editId ? { ...e, ...updated } : e));
    setEditId(null);
    toast?.({ message: "✏️ Expense updated", type: "info" });
  };

  // ================= FILTER =================
  const getFiltered = () => {
    const now     = new Date();
    const keyword = search.toLowerCase().trim();

    return expenses.filter((item) => {
      if (!item.date) return false;
      const date = new Date(item.date);
      if (isNaN(date.getTime())) return false;

      // ── preset filters ──
      if (filter === "today") {
        if (!(date.getFullYear() === now.getFullYear() &&
              date.getMonth()    === now.getMonth()    &&
              date.getDate()     === now.getDate())) return false;
      }
      if (filter === "week") {
        const diff = (now - date) / (1000 * 60 * 60 * 24);
        if (!(diff >= 0 && diff <= 7)) return false;
      }
      if (filter === "month") {
        if (!(date.getMonth()    === now.getMonth() &&
              date.getFullYear() === now.getFullYear())) return false;
      }

      // ── date range ──
      if (dateRange?.from) {
        const from = new Date(dateRange.from);
        from.setHours(0, 0, 0, 0);
        if (date < from) return false;
      }
      if (dateRange?.to) {
        const to = new Date(dateRange.to);
        to.setHours(23, 59, 59, 999);
        if (date > to) return false;
      }

      // ── search ──
      if (!keyword) return true;
      return (
        item.title?.toLowerCase().includes(keyword)    ||
        item.category?.toLowerCase().includes(keyword) ||
        String(item.amount).includes(keyword)
      );
    });
  };

  const filtered = getFiltered();
  const totalAmt = filtered.reduce((s, e) => s + Number(e.amount || 0), 0);

  const exportData = filtered.map(({ id, autoGenerated, aiGenerated, ...rest }) => ({
    title:     rest.title     || "",
    category:  rest.category  || "",
    amount:    Number(rest.amount || 0).toFixed(2),
    date:      rest.date ? new Date(rest.date).toLocaleString() : "",
    recurring: rest.recurring || "none",
  }));

  return (
    <div className="expenses-page">

      <ConfirmModal
        isOpen={confirmOpen}
        onConfirm={confirmDelete}
        onCancel={cancelDelete}
        title="Delete Expense"
        message="Are you sure you want to delete"
        itemName={pendingDeleteName}
      />

      {/* ── HEADER ── */}
      <div className="expenses-header">
        <div>
          <h1>Expenses</h1>
          <p>Track and manage all your expenses</p>
        </div>
        {filtered.length > 0 && (
          <div className="export-btns">
            <button className="export-btn csv" onClick={() => {
              exportCSV(exportData, "expenses");
              toast?.({ message: "📥 Exported as CSV", type: "success" });
            }}>
              <Download size={14} /> CSV
            </button>
            <button className="export-btn pdf" onClick={() => {
              exportPDF(filtered, "expenses", "Expense Report");
              toast?.({ message: "📄 PDF ready", type: "info" });
            }}>
              <FileText size={14} /> PDF
            </button>
          </div>
        )}
      </div>

      <ExpenseForm addExpense={addExpense} />

      {/* ── TOOLBAR ── */}
      <div className="exp-toolbar">
        <div className="exp-filters">
          {FILTER_OPTIONS.map((f) => (
            <button
              key={f.key}
              className={`exp-filter-btn ${filter === f.key && !dateRange ? "active" : ""}`}
              onClick={() => { setFilter(f.key); setDateRange(null); }}
            >
              {f.icon && <span className="exp-filter-icon">{f.icon}</span>}
              <span className="exp-filter-label">{f.label}</span>
              {filter === f.key && !dateRange && (
                <span className="exp-filter-count">{filtered.length}</span>
              )}
            </button>
          ))}

          {/* DATE RANGE */}
          <DateRangeFilter
            active={!!dateRange}
            onApply={(range) => { setDateRange(range); setFilter("all"); }}
            onClear={() => setDateRange(null)}
          />
        </div>

        {filtered.length > 0 && (
          <div className="exp-summary">
            <span className="exp-summary-count">{filtered.length} transactions</span>
            <span className="exp-summary-divider" />
            <span className="exp-summary-total">{fmt(totalAmt)}</span>
          </div>
        )}
      </div>

      {/* ── DATE RANGE INFO ── */}
      {dateRange && (
        <div className="search-info">
          Filtering from <b>{dateRange.from || "beginning"}</b> to <b>{dateRange.to || "today"}</b>
          {" — "}{filtered.length} found
        </div>
      )}

      {search && (
        <div className="search-info">
          Showing results for <b>"{search}"</b> — {filtered.length} found
        </div>
      )}

      {filtered.length === 0 ? (
        <EmptyState
          type={search ? "search" : "expenses"}
          title={search ? "No results found" : "No expenses found"}
          subtitle={
            search       ? `Nothing matched "${search}"` :
            dateRange    ? "No expenses in this date range" :
            filter !== "all" ? "No expenses in this time range" :
            "Add your first expense above"
          }
        />
      ) : (
        <div className="expenses-grid">
          {filtered.map((item) => (
            <div className="expense-card" key={item.id}>

              {editId === item.id ? (
                <div className="edit-box">
                  <input placeholder="Title"    value={editData.title}    onChange={(e) => setEditData({ ...editData, title: e.target.value })} />
                  <input placeholder="Category" value={editData.category} onChange={(e) => setEditData({ ...editData, category: e.target.value })} />
                  <input type="number" placeholder="Amount" value={editData.amount} onChange={(e) => setEditData({ ...editData, amount: e.target.value })} />
                  <input type="datetime-local"  value={editData.date}     onChange={(e) => setEditData({ ...editData, date: e.target.value })} />
                  <select className="recurring-select" value={editData.recurring} onChange={(e) => setEditData({ ...editData, recurring: e.target.value })}>
                    <option value="none">No Recurrence</option>
                    <option value="weekly">🔁 Weekly</option>
                    <option value="monthly">🔁 Monthly</option>
                  </select>
                  <div className="edit-actions">
                    <button className="exp-save-btn"   onClick={saveEdit}>Save</button>
                    <button className="exp-cancel-btn" onClick={() => setEditId(null)}>Cancel</button>
                  </div>
                </div>
              ) : (
                <>
                  <div className="exp-card-top">
                    <div className="exp-card-icon">
                      {item.category?.charAt(0).toUpperCase() || "?"}
                    </div>
                    <div className="exp-card-meta">
                      <h3 className="exp-card-title">{item.title}</h3>
                      <div className="exp-card-tags">
                        <span className="exp-cat-tag">
                          <Tag size={9} />
                          {item.category || "Uncategorized"}
                        </span>
                        {item.recurring && item.recurring !== "none" && (
                          <span className="recurring-badge">
                            <RefreshCw size={9} /> {item.recurring}
                          </span>
                        )}
                        {item.autoGenerated && (
                          <span className="exp-auto-tag">⚡ Auto</span>
                        )}
                      </div>
                    </div>
                  </div>

                  <div className="exp-card-amount">{fmt(item.amount)}</div>

                  <div className="exp-card-footer">
                    <span className="exp-card-date">
                      <Clock size={11} />
                      {item.date
                        ? new Date(item.date).toLocaleDateString("en-US", {
                            month: "short", day: "numeric", year: "numeric",
                          })
                        : "No date"}
                    </span>
                    <div className="exp-card-actions">
                      <button className="exp-action-btn edit"   onClick={() => startEdit(item)} title="Edit"><Pencil size={13} /></button>
                      <button className="exp-action-btn delete" onClick={() => askDelete(item)}  title="Delete"><Trash2 size={13} /></button>
                    </div>
                  </div>
                </>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default Expenses;