import { useState, useMemo } from "react";
import {
  Download, FileText, Pencil, Trash2,
  TrendingUp, Wallet, ArrowDownCircle,
  RefreshCw, Tag, Clock,
} from "lucide-react";
import { useApp }        from "../context/AppContext";
import { useExport }     from "../hooks/useExport";
import EmptyState        from "../components/EmptyState";
import ConfirmModal      from "../components/ConfirmModal";
import DateRangeFilter   from "../components/DateRangeFilter";
import {
  AreaChart, Area, XAxis, YAxis,
  Tooltip, ResponsiveContainer, CartesianGrid,
} from "recharts";

const CATEGORIES = [
  "Salary","Freelance","Business","Investment",
  "Rental","Bonus","Gift","Other",
];

const CAT_COLORS = {
  Salary:     "#22c55e",
  Freelance:  "#6366f1",
  Business:   "#f59e0b",
  Investment: "#06b6d4",
  Rental:     "#8b5cf6",
  Bonus:      "#f97316",
  Gift:       "#ec4899",
  Other:      "#94a3b8",
};

function Income({ toast }) {

  const { incomes, setIncomes, search, fmt, currency } = useApp();

  const [form, setForm] = useState({
    title:"", amount:"", category:"Salary",
    date:"", note:"", recurring:"none",
  });
  const [editId,   setEditId]   = useState(null);
  const [editData, setEditData] = useState({});

  // ── CONFIRM MODAL ──
  const [confirmOpen,       setConfirmOpen]       = useState(false);
  const [pendingDeleteId,   setPendingDeleteId]   = useState(null);
  const [pendingDeleteName, setPendingDeleteName] = useState("");

  // ── DATE RANGE ──
  const [dateRange, setDateRange] = useState(null);

  // ================= ADD =================
  const addIncome = () => {
    if (!form.title || !form.amount || !form.date) return;
    const formatted = {
      ...form,
      title:  form.title.charAt(0).toUpperCase() + form.title.slice(1),
      amount: Number(form.amount),
    };
    setIncomes([{ id: Date.now(), ...formatted }, ...incomes]);
    toast?.({ message: `✅ "${formatted.title}" added`, type: "success" });
    setForm({ title:"", amount:"", category:"Salary", date:"", note:"", recurring:"none" });
  };

  // ================= DELETE =================
  const askDelete = (item) => {
    setPendingDeleteId(item.id);
    setPendingDeleteName(item.title);
    setConfirmOpen(true);
  };

  const confirmDelete = () => {
    setIncomes(incomes.filter((i) => i.id !== pendingDeleteId));
    toast?.({ message: `🗑 "${pendingDeleteName}" deleted`, type: "error" });
    setConfirmOpen(false);
    setPendingDeleteId(null);
    setPendingDeleteName("");
  };

  const cancelDelete = () => {
    setConfirmOpen(false);
    setPendingDeleteId(null);
    setPendingDeleteName("");
  };

  // ================= EDIT =================
  const startEdit = (item) => {
    setEditId(item.id);
    setEditData({
      title:     item.title,
      amount:    item.amount,
      category:  item.category,
      date:      item.date ? new Date(item.date).toISOString().slice(0, 16) : "",
      note:      item.note      || "",
      recurring: item.recurring || "none",
    });
  };

  const saveEdit = () => {
    const updated = {
      ...editData,
      title:  editData.title
        ? editData.title.charAt(0).toUpperCase() + editData.title.slice(1)
        : editData.title,
      amount: Number(editData.amount),
    };
    setIncomes(incomes.map((i) => i.id === editId ? { ...i, ...updated } : i));
    setEditId(null);
    toast?.({ message: "✏️ Income updated", type: "info" });
  };

  // ================= SEARCH + DATE RANGE =================
  const filtered = useMemo(() => {
    const keyword = search.toLowerCase().trim();

    return incomes.filter((i) => {

      // ── search ──
      if (keyword) {
        const matches =
          i.title?.toLowerCase().includes(keyword)    ||
          i.category?.toLowerCase().includes(keyword) ||
          String(i.amount).includes(keyword);
        if (!matches) return false;
      }

      // ── date range ──
      if (dateRange?.from || dateRange?.to) {
        if (!i.date) return false;
        const date = new Date(i.date);
        if (isNaN(date.getTime())) return false;

        if (dateRange.from) {
          const from = new Date(dateRange.from);
          from.setHours(0, 0, 0, 0);
          if (date < from) return false;
        }
        if (dateRange.to) {
          const to = new Date(dateRange.to);
          to.setHours(23, 59, 59, 999);
          if (date > to) return false;
        }
      }

      return true;
    });
  }, [incomes, search, dateRange]);

  // ================= EXPORT =================
  const { exportCSV, exportPDF } = useExport();
  const exportData = filtered.map(({ id, autoGenerated, ...rest }) => ({
    title:     rest.title     || "",
    category:  rest.category  || "",
    amount:    Number(rest.amount || 0).toFixed(2),
    date:      rest.date ? new Date(rest.date).toLocaleString() : "",
    note:      rest.note      || "",
    recurring: rest.recurring || "none",
  }));

  // ================= STATS =================
  const totalIncome = useMemo(() =>
    incomes.reduce((s, i) => s + Number(i.amount || 0), 0), [incomes]);

  const thisMonth = useMemo(() => {
    const now = new Date();
    return incomes
      .filter((i) => {
        const d = new Date(i.date);
        return d.getMonth()    === now.getMonth() &&
               d.getFullYear() === now.getFullYear();
      })
      .reduce((s, i) => s + Number(i.amount || 0), 0);
  }, [incomes]);

  const avgIncome = incomes.length > 0 ? totalIncome / incomes.length : 0;

  // ================= CHART =================
  const monthlyData = useMemo(() => {
    const map = {};
    incomes.forEach((item) => {
      if (!item.date) return;
      const date = new Date(item.date);
      if (isNaN(date.getTime())) return;
      const month = date.toLocaleString("default", { month: "short" });
      map[month] = (map[month] || 0) + Number(item.amount || 0);
    });
    return Object.keys(map).map((key) => ({ month: key, amount: map[key] }));
  }, [incomes]);

  // ================= CATEGORY BREAKDOWN =================
  const categoryBreakdown = useMemo(() => {
    const map = {};
    incomes.forEach((i) => {
      map[i.category] = (map[i.category] || 0) + Number(i.amount || 0);
    });
    return Object.entries(map)
      .sort((a, b) => b[1] - a[1])
      .map(([cat, amt]) => ({
        category: cat,
        amount:   amt,
        pct:      totalIncome > 0 ? Math.round((amt / totalIncome) * 100) : 0,
      }));
  }, [incomes, totalIncome]);

  const totalFiltered = filtered.reduce((s, i) => s + Number(i.amount || 0), 0);

  return (
    <div className="income-page">

      {/* CONFIRM MODAL */}
      <ConfirmModal
        isOpen={confirmOpen}
        onConfirm={confirmDelete}
        onCancel={cancelDelete}
        title="Delete Income"
        message="Are you sure you want to delete"
        itemName={pendingDeleteName}
      />

      {/* ── HEADER ── */}
      <div className="income-header">
        <div>
          <h1>Income</h1>
          <p>Track all your earnings in one place</p>
        </div>
        {filtered.length > 0 && (
          <div className="export-btns">
            <button className="export-btn csv" onClick={() => {
              exportCSV(exportData, "income");
              toast?.({ message: "📥 Exported as CSV", type: "success" });
            }}>
              <Download size={14} /> CSV
            </button>
            <button className="export-btn pdf" onClick={() => {
              exportPDF(filtered, "income", "Income Report");
              toast?.({ message: "📄 PDF ready", type: "info" });
            }}>
              <FileText size={14} /> PDF
            </button>
          </div>
        )}
      </div>

      {/* ── SEARCH INFO ── */}
      {search && (
        <div className="search-info">
          Showing results for <b>"{search}"</b> — {filtered.length} found
        </div>
      )}

      {/* ── STATS ── */}
      <div className="income-stats">
        <div className="income-stat-card green">
          <div className="income-stat-icon"><Wallet size={20} /></div>
          <div><p>Total Income</p><h2>{fmt(totalIncome)}</h2></div>
        </div>
        <div className="income-stat-card blue">
          <div className="income-stat-icon"><ArrowDownCircle size={20} /></div>
          <div><p>This Month</p><h2>{fmt(thisMonth)}</h2></div>
        </div>
        <div className="income-stat-card purple">
          <div className="income-stat-icon"><TrendingUp size={20} /></div>
          <div><p>Avg per Entry</p><h2>{fmt(avgIncome)}</h2></div>
        </div>
      </div>

      {/* ── FORM + CHART ── */}
      <div className="income-top-row">

        <div className="income-form-card">
          <h3>Add Income</h3>
          <p>Record a new income entry</p>
          <div className="income-form">
            <input
              type="text"
              placeholder="Title (e.g. Monthly Salary)"
              value={form.title}
              onChange={(e) => setForm({ ...form, title: e.target.value })}
            />
            <input
              type="number"
              placeholder={`Amount (${currency})`}
              value={form.amount}
              onChange={(e) => setForm({ ...form, amount: e.target.value })}
            />
            <select
              value={form.category}
              onChange={(e) => setForm({ ...form, category: e.target.value })}
            >
              {CATEGORIES.map((c) => <option key={c} value={c}>{c}</option>)}
            </select>
            <input
              type="datetime-local"
              value={form.date}
              onChange={(e) => setForm({ ...form, date: e.target.value })}
            />
            <input
              type="text"
              placeholder="Note (optional)"
              value={form.note}
              onChange={(e) => setForm({ ...form, note: e.target.value })}
            />
            <select
              className="recurring-select"
              value={form.recurring}
              onChange={(e) => setForm({ ...form, recurring: e.target.value })}
            >
              <option value="none">No Recurrence</option>
              <option value="weekly">🔁 Weekly</option>
              <option value="monthly">🔁 Monthly</option>
            </select>
            <button
              className="income-add-btn"
              onClick={addIncome}
              disabled={!form.title || !form.amount || !form.date}
            >
              + Add Income
            </button>
          </div>
        </div>

        <div className="income-chart-card">
          <div className="monthly-chart-header">
            <div>
              <h3>Monthly Income</h3>
              <p className="chart-sub">Earnings trend over time</p>
            </div>
            {monthlyData.length > 0 && (
              <div className="income-total-pill">{fmt(totalIncome)}</div>
            )}
          </div>

          {monthlyData.length === 0 ? (
            <EmptyState
              type="income"
              title="No monthly data yet"
              subtitle="Add income entries to see your earnings trend"
            />
          ) : (
            <ResponsiveContainer width="100%" height={240}>
              <AreaChart data={monthlyData} margin={{ top: 10, right: 10, left: -10, bottom: 0 }}>
                <defs>
                  <linearGradient id="incomeGrad" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%"   stopColor="#22c55e" stopOpacity={0.35} />
                    <stop offset="100%" stopColor="#22c55e" stopOpacity={0}    />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)" vertical={false} />
                <XAxis dataKey="month" tick={{ fill: "var(--text-secondary)", fontSize: 11 }} axisLine={false} tickLine={false} dy={8} />
                <YAxis tick={{ fill: "var(--text-secondary)", fontSize: 11 }} axisLine={false} tickLine={false}
                  tickFormatter={(v) => `${currency}${v >= 1000 ? (v/1000).toFixed(1)+"k" : v}`}
                />
                <Tooltip
                  contentStyle={{ background: "var(--card-bg)", border: "1px solid var(--border)", borderRadius: "12px", padding: "10px 14px" }}
                  labelStyle={{ color: "var(--text)", fontWeight: 600, fontSize: 13 }}
                  itemStyle={{ color: "#22c55e", fontWeight: 600, fontSize: 13 }}
                  formatter={(v) => [fmt(v), "Income"]}
                />
                <Area
                  type="monotone" dataKey="amount" stroke="#22c55e" strokeWidth={2.5}
                  fill="url(#incomeGrad)"
                  dot={{ r: 4, fill: "#22c55e", strokeWidth: 2, stroke: "var(--card-bg)" }}
                  activeDot={{ r: 6, fill: "#22c55e", stroke: "var(--card-bg)", strokeWidth: 2 }}
                />
              </AreaChart>
            </ResponsiveContainer>
          )}

          {categoryBreakdown.length > 0 && (
            <div className="income-cat-breakdown">
              {categoryBreakdown.map((c) => (
                <div className="income-cat-row" key={c.category}>
                  <div className="income-cat-left">
                    <span className="income-cat-dot" style={{ background: CAT_COLORS[c.category] || "#94a3b8" }} />
                    <span className="income-cat-name">{c.category}</span>
                  </div>
                  <div className="income-cat-right">
                    <div className="income-cat-bar-wrap">
                      <div className="income-cat-bar" style={{ width: `${c.pct}%`, background: CAT_COLORS[c.category] || "#94a3b8" }} />
                    </div>
                    <span className="income-cat-amt">{fmt(c.amount)}</span>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

      </div>

      {/* ── TOOLBAR ── */}
      <div className="exp-toolbar" style={{ marginBottom: 16 }}>
        <div className="exp-filters">
          <DateRangeFilter
            active={!!dateRange}
            onApply={(range) => setDateRange(range)}
            onClear={() => setDateRange(null)}
          />
        </div>
        {filtered.length > 0 && (
          <div className="exp-summary">
            <span className="exp-summary-count">{filtered.length} entries</span>
            <span className="exp-summary-divider" />
            <span className="exp-summary-total">{fmt(totalFiltered)}</span>
          </div>
        )}
      </div>

      {/* ── DATE RANGE INFO ── */}
      {dateRange && (
        <div className="search-info">
          Filtering from <b>{dateRange.from || "beginning"}</b> to{" "}
          <b>{dateRange.to || "today"}</b> — {filtered.length} found
        </div>
      )}

      {/* ── LIST ── */}
      {filtered.length === 0 ? (
        <EmptyState
          type={search ? "search" : "income"}
          title={search ? "No results found" : dateRange ? "No income in this range" : "No income recorded"}
          subtitle={
            search    ? `Nothing matched "${search}"` :
            dateRange ? "Try a different date range" :
            "Add your first income entry above"
          }
        />
      ) : (
        <div className="expenses-grid">
          {filtered.map((item) => (
            <div className="expense-card" key={item.id}>

              {editId === item.id ? (

                /* ── EDIT MODE ── */
                <div className="edit-box">
                  <input
                    placeholder="Title"
                    value={editData.title}
                    onChange={(e) => setEditData({ ...editData, title: e.target.value })}
                  />
                  <input
                    type="number"
                    placeholder="Amount"
                    value={editData.amount}
                    onChange={(e) => setEditData({ ...editData, amount: e.target.value })}
                  />
                  <select
                    value={editData.category}
                    onChange={(e) => setEditData({ ...editData, category: e.target.value })}
                  >
                    {CATEGORIES.map((c) => <option key={c} value={c}>{c}</option>)}
                  </select>
                  <input
                    type="datetime-local"
                    value={editData.date}
                    onChange={(e) => setEditData({ ...editData, date: e.target.value })}
                  />
                  <input
                    placeholder="Note"
                    value={editData.note}
                    onChange={(e) => setEditData({ ...editData, note: e.target.value })}
                  />
                  <select
                    className="recurring-select"
                    value={editData.recurring || "none"}
                    onChange={(e) => setEditData({ ...editData, recurring: e.target.value })}
                  >
                    <option value="none">No Recurrence</option>
                    <option value="weekly">🔁 Weekly</option>
                    <option value="monthly">🔁 Monthly</option>
                  </select>
                  <div className="edit-actions">
                    <button className="exp-save-btn"   onClick={saveEdit}>Save</button>
                    <button className="exp-cancel-btn" onClick={() => setEditId(null)}>Cancel</button>
                  </div>
                </div>

              ) : (

                /* ── VIEW MODE ── */
                <>
                  <div className="exp-card-top">
                    <div className="exp-card-icon" style={{
                      background: "linear-gradient(135deg, #22c55e, #16a34a)",
                      color: "white",
                      boxShadow: "0 4px 10px rgba(34,197,94,0.3)",
                    }}>
                      {item.category?.charAt(0).toUpperCase() || "?"}
                    </div>
                    <div className="exp-card-meta">
                      <h3 className="exp-card-title">{item.title}</h3>
                      <div className="exp-card-tags">
                        <span className="exp-cat-tag">
                          <Tag size={9} />
                          {item.category || "Uncategorized"}
                        </span>
                        {item.recurring && item.recurring !== "none" && (
                          <span className="recurring-badge">
                            <RefreshCw size={9} /> {item.recurring}
                          </span>
                        )}
                        {item.autoGenerated && (
                          <span className="exp-auto-tag">⚡ Auto</span>
                        )}
                      </div>
                    </div>
                  </div>

                  <div className="exp-card-amount" style={{
                    background: "linear-gradient(135deg, #22c55e 0%, #16a34a 100%)",
                    WebkitBackgroundClip: "text",
                    WebkitTextFillColor: "transparent",
                    backgroundClip: "text",
                  }}>
                    +{fmt(item.amount)}
                  </div>

                  <div className="exp-card-footer">
                    <span className="exp-card-date">
                      <Clock size={11} />
                      {item.date
                        ? new Date(item.date).toLocaleDateString("en-US", {
                            month: "short", day: "numeric", year: "numeric",
                          })
                        : "No date"}
                    </span>
                    <div className="exp-card-actions">
                      <button className="exp-action-btn edit"   onClick={() => startEdit(item)} title="Edit"><Pencil size={13} /></button>
                      <button className="exp-action-btn delete" onClick={() => askDelete(item)}  title="Delete"><Trash2 size={13} /></button>
                    </div>
                  </div>

                  {item.note && (
                    <div className="inc-card-note">{item.note}</div>
                  )}
                </>

              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default Income;